spring:
  application:
    name: tenant-job-scheduler

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:job_scheduler}
    username: ${POSTGRES_USER:job_scheduler_app}
    password: ${POSTGRES_PASSWORD:ivan}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: false
    baseline-on-migrate: true
    schemas: public

server:
  port: ${BACKEND_PORT:8080}

scheduler:
  concurrency:
    global-max: 5 #The global-max value should not be over 50 as this is what our current thread pool size is
    tenant-max: 2
    target-max: 1
  worker:
    pool-size: 5
    poll-interval-ms: 10000

logging:
  level:
    com.scheduler: INFO
    org.springframework.web: INFO
    org.springframework.transaction: INFO
